apiVersion: v1
kind: ConfigMap
metadata:
  name: kouho-config
  namespace: default
data:
  DB_HOST: "db-kouho.c1egoi0icx56.ap-southeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USER: "admin"
  DB_NAME: "db_kouho"
  AWS_REGION: "ap-southeast-2"
  S3_BUCKET: "kouho-vid-s3-bucket-590144423099-ap-southeast-2-an"
  PORT: "8080"